### ISSUE TITLE
Visualize community garden with ASCII (colored)

### ISSUE THREAD

**Issue by JStaxton** [michael-lazar/astrobotany#108]
Dear Astrobotany community,

I would like to propose a change to the image of the community garden page.

The image consists of single characters representing one flower. With correct coloring and growth stage each plant is drawn in a fixed position. When the plant is dry it gets colorless. This way you can easily see the condition of the whole garden.
As a bonus I added the koi pond with the cute koi showing off the blessed color.
Can you spot your flower? :)

Before and After comparison
![comparison](https://user-images.githubusercontent.com/46413343/142727218-0c25a49d-5b49-432c-a966-5856fdd647cf.png)

Timelapse (each image 1 day - 2 weeks total)
![grey](https://user-images.githubusercontent.com/46413343/142727273-7511169c-0ba7-4f48-80a1-62e766cdc6f4.gif)

All code is done in python. If this feature is of interest I'd try to create a pull request, hopefully with the help of @michael-lazar 

Have a nice day and see you in the garden.
jstaxton

**Comment by michael-lazar** [comment]
WOW I LOVE IT! 😍

**Comment by JStaxton** [comment]
I tried to commit a first file showing the creation of this image.

**Comment by michael-lazar** [comment]
@JStaxton Thanks! It will take a little while to integrate this, and to be honest I'll probably end up re-writing most of the code to better fit into the existing framework. But it's super useful to have your PR code as a reference to work off of.

**Comment by JStaxton** [comment]
@michael-lazar Thats absolutely no problem. The important part is the idea and inspiration. If my code and/or comments help to convey that, I'm happy. 
Looking forward to see your implementation.
