### ISSUE TITLE
Trouble signing in

### ISSUE THREAD

**Issue by Obspogon** [michael-lazar/astrobotany#113]
### I deleted my old certificate and want to sign in. So I created a new certificate and tried to link to my existing account, but got this:

![image](https://user-images.githubusercontent.com/72287594/150458792-e125d68b-703d-4e88-9452-6035a129c3df.png)

**Comment by michael-lazar** [comment]
Send me an email with your username and I'll reset your password and send it to you: lazar.michael22@gmail.com

**Comment by Obspogon** [comment]
Got in, thanks.
