### ISSUE TITLE
Plant page renders incorrectly

### ISSUE THREAD

**Issue by wesleywerner** [michael-lazar/astrobotany#116]
One of the astro botanists reported their plant page not rendering correctly, opening an issue for this.

Plant URL: //astrobotany.mozz.us/app/visit/39d4f7999bc04ad7940132f514eef316

![Screenshot_20220518-185258](https://user-images.githubusercontent.com/551913/168999731-148df9e5-af7b-4f9a-ae26-b1361467c187.png)

[39d4f7999bc04ad7940132f514eef316.txt](https://github.com/michael-lazar/astrobotany/files/8714731/39d4f7999bc04ad7940132f514eef316.txt)

**Comment by michael-lazar** [comment]
Looks like they did it on purpose as a joke? They entered their plant's name as ``"\n\n\n\n\n\n\n\n`` so this is how it shows up.

**Comment by wesleywerner** [comment]
Closing this issue, as it is not a bug
